var g_resources = [

	{ src: "images/cursor.png" },
	{ src: "images/marker.png" },
	{ src: "images/marker_none.png" },
	// { src: "images/arrow_glow.png" },
	// { src: "images/arrow.png" },
	{ src: "images/bar_bg.png" },
	{ src: "images/bar_border.png" },
	{ src: "images/blocks/air.png" },
	// { src: "images/blocks/bone.png" },
	{ src: "images/blocks/checkpoint.png" },
	{ src: "images/blocks/coin.png" },
	{ src: "images/blocks/dirt.png" },
	// { src: "images/blocks/dirt_float.png" },
	{ src: "images/blocks/grass_touched.png" },
	{ src: "images/blocks/grass.png" },
	{ src: "images/blocks/metal.png" },
	// { src: "images/coin/coin0.png" },
	// { src: "images/coin/coin1.png" },
	// { src: "images/coin/coin2.png" },
	// { src: "images/coin/coin3.png" },
	// { src: "images/coin/coin4.png" },
	// { src: "images/coin/coin5.png" },

	// { src: "images/crosshair.png" },
	{ src: "images/hp_green.png" },
	// { src: "images/monsters/soul0.png" },
	// { src: "images/monsters/soul1.png" },
	// { src: "images/monsters/soul2.png" },
	// { src: "images/monsters/soul3.png" },
	// { src: "images/monsters/soul4.png" },
	// { src: "images/monsters/soul5.png" },
	{ src: "images/poring0.png" },
	{ src: "images/poring1.png" },
	{ src: "images/poring2.png" },
	{ src: "images/sight.png" },
	{ src: "images/sky.png" },
	{ src: "images/sp.png" },
	// { src: "images/tree1.png" },
	// { src: "images/tree2.png" },

	
	{ src: "images/crosshair/0.png" },
	{ src: "images/crosshair/1.png" },
	{ src: "images/crosshair/2.png" },
	{ src: "images/crosshair/3.png" },

];